# Generated by Django 5.2.7 on 2025-10-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_distributor'),
    ]

    operations = [
        migrations.CreateModel(
            name='student2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('DOB', models.DateField()),
            ],
        ),
    ]
