# Generated by Django 5.2.7 on 2025-10-09 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='person',
            new_name='person_name',
        ),
    ]
