# Generated by Django 5.2.7 on 2025-10-10 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_person_person_person_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['book_name']},
        ),
        migrations.AlterModelTable(
            name='book',
            table='book_table',
        ),
    ]
