# Generated by Django 5.2.7 on 2025-10-10 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_book_options_alter_book_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('book_name', '-author_id'), 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
    ]
