# Generated by Django 5.2.7 on 2025-10-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_customer_employee_alter_book_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('can_delete', 'Can delete record'), ('can_update', 'Can update record')]},
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('age__gte', 12)), name='age_gte_12'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('email', 'mobile_number'), name='unique_email_mobile'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('age__gte', 20)), name='age_gte_20'),
        ),
    ]
