# Generated by Django 5.2.7 on 2025-10-15 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='id',
            new_name='uuid',
        ),
    ]
